/* Cache-first service worker so Dino Bob plays offline once installed. */

var CACHE = 'dinobob-v88-juice';
var FILES = [
  '.',
  'index.html',
  'css/style.css',
  'js/tuning.js',
  'js/data.js',
  'js/save.js',
  'js/audio.js',
  'js/sprites.js',
  'js/art.js',
  'js/stages.js',
  'js/game.js',
  'js/ui.js',
  'js/changelog.js',
  'js/main.js',
  'assets/audio/music_loop.ogg',
  'assets/audio/music_loop.mp3',
  'intro/intro.dc.html',
  'intro/support.js',
  'intro/intro.jsx',
  'intro/assets/forest.png',
  'intro/assets/dino_0.png',
  'intro/assets/dino_1.png',
  'intro/assets/dino_2.png',
  'intro/assets/dino_3.png',
  'intro/assets/bow.png',
  'intro/assets/arrow_basic.png',
  'intro/assets/arrow_fire.png',
  'intro/assets/arrow_firegold.png',
  'intro/assets/arrow_gold.png',
  'intro/assets/arrow_ice.png',
  'intro/assets/balloon.png',
  'intro/assets/target.png',
  'intro/assets/coin.png',
  'manifest.webmanifest',
  'assets/icons/icon-192.png',
  'assets/icons/icon-512.png',
  // every sprite the game can draw (all confirmed present on disk) so a cache
  // version bump never strands the game with blank art while offline
  'assets/sprites/char_dinobob.png',
  'assets/sprites/char_ninja.png',
  'assets/sprites/char_astronaut.png',
  'assets/sprites/char_robot.png',
  'assets/sprites/char_bear.png',
  'assets/sprites/arm_dinobob_upper.png',
  'assets/sprites/arm_dinobob_bowhand.png',
  'assets/sprites/arm_dinobob_stringhand.png',
  'assets/sprites/arm_ninja_upper.png',
  'assets/sprites/arm_ninja_bowhand.png',
  'assets/sprites/arm_ninja_stringhand.png',
  'assets/sprites/arm_astronaut_upper.png',
  'assets/sprites/arm_astronaut_bowhand.png',
  'assets/sprites/arm_astronaut_stringhand.png',
  'assets/sprites/arm_robot_upper.png',
  'assets/sprites/arm_robot_bowhand.png',
  'assets/sprites/arm_robot_stringhand.png',
  'assets/sprites/arm_bear_upper.png',
  'assets/sprites/arm_bear_bowhand.png',
  'assets/sprites/arm_bear_stringhand.png',
  'assets/sprites/arrow_wooden.png',
  'assets/sprites/arrow_fire.png',
  'assets/sprites/arrow_ice.png',
  'assets/sprites/arrow_lightning.png',
  'assets/sprites/arrow_obsidian.png',
  'assets/sprites/bow.png',
  'assets/sprites/balloon.png',
  'assets/sprites/plane_flyby.webp',
  'assets/sprites/bg_meadow.webp',
  'assets/sprites/bg_mountain.webp',
  'assets/sprites/target.png',
  'assets/sprites/coin.png',
  'assets/sprites/blackhole_0.png',
  'assets/sprites/blackhole_1.png',
  'assets/sprites/blackhole_2.png',
  'assets/sprites/chest_closed.png',
  'assets/sprites/chest_semi.png',
  'assets/sprites/chest_open.png',
  'assets/sprites/chest_3d_0.png',
  'assets/sprites/chest_3d_1.png',
  'assets/sprites/chest_3d_2.png',
  'assets/sprites/chest_3d_3.png',
  'assets/sprites/chest_3d_4.png',
  'assets/sprites/chest_3d_5.png',
  'assets/sprites/chest_3d_6.png',
  'assets/sprites/chest_3d_7.png',
  'assets/sprites/fruit_apple.png',
  'assets/sprites/fruit_banana.png',
  'assets/sprites/fruit_pineapple.png',
  'assets/sprites/fruit_strawberry.png',
  'assets/sprites/fruit_orange.png',
  'assets/sprites/fruit_grapes.png',
  'assets/sprites/fruit_pear.png',
  'assets/sprites/fruit_cherry.png',
  'assets/sprites/fruit_watermelon.png',
  'assets/sprites/hat_cap.png',
  'assets/sprites/hat_viking.png',
  'assets/sprites/hat_robin.png',
  'assets/sprites/hat_bandana.png',
  'assets/sprites/hat_wizard.png',
  'assets/sprites/hat_crown.png',
  'assets/sprites/hat_pirate.png',
  'assets/sprites/hat_dino.png',
  'assets/sprites/hat_astro.png',
  // V5 art overhaul
  'assets/sprites/char_trixie.png',
  'assets/sprites/arm_trixie_upper.png',
  'assets/sprites/arm_trixie_bowhand.png',
  'assets/sprites/arm_trixie_stringhand.png',
  'assets/sprites/char_dinobob_ruby.png',
  'assets/sprites/char_dinobob_grape.png',
  'assets/sprites/char_dinobob_gold.png',
  'assets/sprites/char_dinobob_mint.png',
  'assets/sprites/char_dinobob_shiny.png',
  'assets/sprites/boss_moonstone.webp',
  'assets/sprites/boss_moonstone_cracked.webp',
  'assets/sprites/boss_moonstone_broken.webp',
  'assets/sprites/boss_moonstone_3d_0.webp',
  'assets/sprites/boss_moonstone_3d_1.webp',
  'assets/sprites/boss_moonstone_3d_2.webp',
  'assets/sprites/boss_moonstone_3d_3.webp',
  'assets/sprites/boss_moonstone_3d_4.webp',
  'assets/sprites/boss_moonstone_3d_5.webp',
  'assets/sprites/bg_moon_cave.webp',
  'assets/sprites/bg_starlight.webp',
  'assets/sprites/bg_sunset_beach.webp',
  'assets/sprites/bg_underwater.webp',
  'assets/sprites/adventure_map.webp',
  // integrated in-game archer poses
  'assets/sprites/char_dinobob_archer.png',
  'assets/sprites/char_ninja_archer.png',
  'assets/sprites/char_astronaut_archer.png',
  'assets/sprites/char_robot_archer.png',
  'assets/sprites/char_bear_archer.png',
  'assets/sprites/char_trixie_archer.png',
  // V6 'Real Objects' art (all WebP)
  'assets/sprites/target_stand.webp',
  'assets/sprites/target_3d_0.webp',
  'assets/sprites/target_3d_1.webp',
  'assets/sprites/target_3d_2.webp',
  'assets/sprites/target_3d_3.webp',
  'assets/sprites/target_3d_4.webp',
  'assets/sprites/target_3d_5.webp',
  'assets/sprites/pickup_arrows.webp',
  'assets/sprites/pickup_slowmo.webp',
  'assets/sprites/fruit_apple_3d_0.webp',
  'assets/sprites/fruit_apple_3d_1.webp',
  'assets/sprites/fruit_apple_3d_2.webp',
  'assets/sprites/fruit_apple_3d_3.webp',
  'assets/sprites/fruit_apple_3d_4.webp',
  'assets/sprites/fruit_apple_3d_5.webp',
  'assets/sprites/fruit_banana_3d_0.webp',
  'assets/sprites/fruit_banana_3d_1.webp',
  'assets/sprites/fruit_banana_3d_2.webp',
  'assets/sprites/fruit_banana_3d_3.webp',
  'assets/sprites/fruit_banana_3d_4.webp',
  'assets/sprites/fruit_banana_3d_5.webp',
  'assets/sprites/fruit_watermelon_3d_0.webp',
  'assets/sprites/fruit_watermelon_3d_1.webp',
  'assets/sprites/fruit_watermelon_3d_2.webp',
  'assets/sprites/fruit_watermelon_3d_3.webp',
  'assets/sprites/fruit_watermelon_3d_4.webp',
  'assets/sprites/fruit_watermelon_3d_5.webp',
  'assets/sprites/fg_meadow.webp',
  'assets/sprites/fg_mountain.webp',
  'assets/sprites/fg_sunset_beach.webp',
  'assets/sprites/fg_starlight.webp',
  'assets/sprites/fg_underwater.webp',
  'assets/sprites/fg_moon_cave.webp',
  'assets/sprites/char_dinobob_draw0.png',
  'assets/sprites/char_dinobob_draw1.png',
  'assets/sprites/char_dinobob_draw2.png',
  // baked-toy turntables: procedural Blender balloon + coin (WebP)
  'assets/sprites/balloon_3d_0.webp',
  'assets/sprites/balloon_3d_1.webp',
  'assets/sprites/balloon_3d_2.webp',
  'assets/sprites/balloon_3d_3.webp',
  'assets/sprites/balloon_3d_4.webp',
  'assets/sprites/balloon_3d_5.webp',
  'assets/sprites/coin_3d_0.webp',
  'assets/sprites/coin_3d_1.webp',
  'assets/sprites/coin_3d_2.webp',
  'assets/sprites/coin_3d_3.webp',
  'assets/sprites/coin_3d_4.webp',
  'assets/sprites/coin_3d_5.webp',
  // depth pass: sliced background planes + nearest foreground twin strips
  'assets/sprites/bg_meadow_far.webp', 'assets/sprites/bg_meadow_mid.webp',
  'assets/sprites/bg_mountain_far.webp', 'assets/sprites/bg_mountain_mid.webp',
  'assets/sprites/bg_sunset_beach_far.webp', 'assets/sprites/bg_sunset_beach_mid.webp',
  'assets/sprites/bg_starlight_far.webp', 'assets/sprites/bg_starlight_mid.webp',
  'assets/sprites/bg_underwater_far.webp', 'assets/sprites/bg_underwater_mid.webp',
  'assets/sprites/bg_moon_cave_far.webp', 'assets/sprites/bg_moon_cave_mid.webp',
  'assets/sprites/fg2_meadow.webp', 'assets/sprites/fg2_mountain.webp',
  'assets/sprites/fg2_sunset_beach.webp', 'assets/sprites/fg2_starlight.webp',
  'assets/sprites/fg2_underwater.webp', 'assets/sprites/fg2_moon_cave.webp',
  // baked 3D gear: lit toy bow + rolling arrow turntables per type
  'assets/sprites/bow_3d_0.webp',
  'assets/sprites/arrow_wooden_3d_0.webp', 'assets/sprites/arrow_wooden_3d_1.webp',
  'assets/sprites/arrow_wooden_3d_2.webp', 'assets/sprites/arrow_wooden_3d_3.webp',
  'assets/sprites/arrow_wooden_3d_4.webp', 'assets/sprites/arrow_wooden_3d_5.webp',
  'assets/sprites/arrow_fire_3d_0.webp', 'assets/sprites/arrow_fire_3d_1.webp',
  'assets/sprites/arrow_fire_3d_2.webp', 'assets/sprites/arrow_fire_3d_3.webp',
  'assets/sprites/arrow_fire_3d_4.webp', 'assets/sprites/arrow_fire_3d_5.webp',
  'assets/sprites/arrow_ice_3d_0.webp', 'assets/sprites/arrow_ice_3d_1.webp',
  'assets/sprites/arrow_ice_3d_2.webp', 'assets/sprites/arrow_ice_3d_3.webp',
  'assets/sprites/arrow_ice_3d_4.webp', 'assets/sprites/arrow_ice_3d_5.webp',
  'assets/sprites/arrow_lightning_3d_0.webp', 'assets/sprites/arrow_lightning_3d_1.webp',
  'assets/sprites/arrow_lightning_3d_2.webp', 'assets/sprites/arrow_lightning_3d_3.webp',
  'assets/sprites/arrow_lightning_3d_4.webp', 'assets/sprites/arrow_lightning_3d_5.webp',
  'assets/sprites/arrow_obsidian_3d_0.webp', 'assets/sprites/arrow_obsidian_3d_1.webp',
  'assets/sprites/arrow_obsidian_3d_2.webp', 'assets/sprites/arrow_obsidian_3d_3.webp',
  'assets/sprites/arrow_obsidian_3d_4.webp', 'assets/sprites/arrow_obsidian_3d_5.webp',
  // cinematic title backdrop (tools/title_scene.py, CSS-referenced)
  'assets/sprites/title_scene.webp',
  // the Crab King: V7 contract boss_crab_3d_* (900px damage turntable)
  'assets/sprites/boss_crab_3d_0.webp', 'assets/sprites/boss_crab_3d_1.webp',
  'assets/sprites/boss_crab_3d_2.webp', 'assets/sprites/boss_crab_3d_3.webp',
  'assets/sprites/boss_crab_3d_4.webp', 'assets/sprites/boss_crab_3d_5.webp',
  // the Angler Golem: V7 contract boss_angler_3d_* (900px)
  'assets/sprites/boss_angler_3d_0.webp', 'assets/sprites/boss_angler_3d_1.webp',
  'assets/sprites/boss_angler_3d_2.webp', 'assets/sprites/boss_angler_3d_3.webp',
  'assets/sprites/boss_angler_3d_4.webp', 'assets/sprites/boss_angler_3d_5.webp',
  // Oak Guardian / Storm Roc / Aurora Wisp King / Prism Serpent
  'assets/sprites/boss_oak_3d_0.webp', 'assets/sprites/boss_oak_3d_1.webp',
  'assets/sprites/boss_oak_3d_2.webp', 'assets/sprites/boss_oak_3d_3.webp',
  'assets/sprites/boss_oak_3d_4.webp', 'assets/sprites/boss_oak_3d_5.webp',
  'assets/sprites/boss_roc_3d_0.webp', 'assets/sprites/boss_roc_3d_1.webp',
  'assets/sprites/boss_roc_3d_2.webp', 'assets/sprites/boss_roc_3d_3.webp',
  'assets/sprites/boss_roc_3d_4.webp', 'assets/sprites/boss_roc_3d_5.webp',
  'assets/sprites/boss_aurora_3d_0.webp', 'assets/sprites/boss_aurora_3d_1.webp',
  'assets/sprites/boss_aurora_3d_2.webp', 'assets/sprites/boss_aurora_3d_3.webp',
  'assets/sprites/boss_aurora_3d_4.webp', 'assets/sprites/boss_aurora_3d_5.webp',
  'assets/sprites/boss_prism_3d_0.webp', 'assets/sprites/boss_prism_3d_1.webp',
  'assets/sprites/boss_prism_3d_2.webp', 'assets/sprites/boss_prism_3d_3.webp',
  'assets/sprites/boss_prism_3d_4.webp', 'assets/sprites/boss_prism_3d_5.webp',
  'assets/sprites/pet_ptero_0.webp',
  'assets/sprites/pet_ptero_1.webp',
  'assets/sprites/pet_ptero_2.webp',
  'assets/sprites/pet_ptero_3.webp',
  'assets/sprites/pet_ptero_4.webp',
  'assets/sprites/pet_ptero_5.webp',
  'assets/sprites/pet_turtle_0.webp',
  'assets/sprites/pet_turtle_1.webp',
  'assets/sprites/pet_turtle_2.webp',
  'assets/sprites/pet_turtle_3.webp',
  'assets/sprites/pet_turtle_4.webp',
  'assets/sprites/pet_turtle_5.webp',
  'assets/sprites/pet_firefly_0.webp',
  'assets/sprites/pet_firefly_1.webp',
  'assets/sprites/pet_firefly_2.webp',
  'assets/sprites/pet_firefly_3.webp',
  'assets/sprites/pet_firefly_4.webp',
  'assets/sprites/pet_firefly_5.webp',
  'assets/sprites/pet_bunbun_0.webp',
  'assets/sprites/pet_bunbun_1.webp',
  'assets/sprites/pet_bunbun_2.webp',
  'assets/sprites/pet_bunbun_3.webp',
  'assets/sprites/pet_bunbun_4.webp',
  'assets/sprites/pet_bunbun_5.webp',
  'assets/sprites/obstacle_shield.webp',
  'assets/sprites/obstacle_wall.webp',
  // Menu/preview hero turntables (decorative; gameplay archer poses unchanged)
  'assets/sprites/char_dinobob_3d_0.webp', 'assets/sprites/char_dinobob_3d_1.webp',
  'assets/sprites/char_dinobob_3d_2.webp', 'assets/sprites/char_dinobob_3d_3.webp',
  'assets/sprites/char_dinobob_3d_4.webp', 'assets/sprites/char_dinobob_3d_5.webp',
  'assets/sprites/char_ninja_3d_0.webp', 'assets/sprites/char_ninja_3d_1.webp',
  'assets/sprites/char_ninja_3d_2.webp', 'assets/sprites/char_ninja_3d_3.webp',
  'assets/sprites/char_ninja_3d_4.webp', 'assets/sprites/char_ninja_3d_5.webp',
  'assets/sprites/char_astronaut_3d_0.webp', 'assets/sprites/char_astronaut_3d_1.webp',
  'assets/sprites/char_astronaut_3d_2.webp', 'assets/sprites/char_astronaut_3d_3.webp',
  'assets/sprites/char_astronaut_3d_4.webp', 'assets/sprites/char_astronaut_3d_5.webp',
  'assets/sprites/char_robot_3d_0.webp', 'assets/sprites/char_robot_3d_1.webp',
  'assets/sprites/char_robot_3d_2.webp', 'assets/sprites/char_robot_3d_3.webp',
  'assets/sprites/char_robot_3d_4.webp', 'assets/sprites/char_robot_3d_5.webp',
  'assets/sprites/char_bear_3d_0.webp', 'assets/sprites/char_bear_3d_1.webp',
  'assets/sprites/char_bear_3d_2.webp', 'assets/sprites/char_bear_3d_3.webp',
  'assets/sprites/char_bear_3d_4.webp', 'assets/sprites/char_bear_3d_5.webp',
  'assets/sprites/char_trixie_3d_0.webp', 'assets/sprites/char_trixie_3d_1.webp',
  'assets/sprites/char_trixie_3d_2.webp', 'assets/sprites/char_trixie_3d_3.webp',
  'assets/sprites/char_trixie_3d_4.webp', 'assets/sprites/char_trixie_3d_5.webp',
  // 3D prototype — Three r160 (UMD + ES modules, offline via importmap)
  '3d.html',
  'js/game3d.js',
  'js/vendor/three.min.js',
  'js/vendor/three.module.js',
  'js/vendor/GLTFLoader.js',
  'js/vendor/GLTFLoader.module.js',
  'js/vendor/loaders/GLTFLoader.js',
  'js/vendor/utils/BufferGeometryUtils.js',
  'assets/models/pet_ptero.glb'
];

self.addEventListener('install', function (e) {
  e.waitUntil(
    caches.open(CACHE).then(function (c) { return c.addAll(FILES); }).then(function () {
      return self.skipWaiting();
    })
  );
});

self.addEventListener('activate', function (e) {
  e.waitUntil(
    caches.keys().then(function (keys) {
      return Promise.all(keys.map(function (k) {
        if (k !== CACHE) return caches.delete(k);
      }));
    }).then(function () { return self.clients.claim(); })
  );
});

self.addEventListener('fetch', function (e) {
  e.respondWith(
    caches.match(e.request).then(function (hit) {
      return hit || fetch(e.request).then(function (res) {
        // cache same-origin gets (and the Google fonts) as we go
        if (e.request.method === 'GET' && res.status === 200) {
          var copy = res.clone();
          caches.open(CACHE).then(function (c) { c.put(e.request, copy); });
        }
        return res;
      });
    }).catch(function () { return caches.match('index.html'); })
  );
});
